# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/annabakas/othello-project-annabakas

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/annabakas/othello-project-annabakas

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/annabakas/othello-project-annabakas/CMakeFiles /home/annabakas/othello-project-annabakas/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/annabakas/othello-project-annabakas/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named othello_tests

# Build rule for target.
othello_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 othello_tests
.PHONY : othello_tests

# fast build rule for target.
othello_tests/fast:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/build
.PHONY : othello_tests/fast

#=============================================================================
# Target rules for targets named othello

# Build rule for target.
othello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 othello
.PHONY : othello

# fast build rule for target.
othello/fast:
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/build
.PHONY : othello/fast

gameboard.o: gameboard.c.o

.PHONY : gameboard.o

# target to build an object file
gameboard.c.o:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/gameboard.c.o
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/gameboard.c.o
.PHONY : gameboard.c.o

gameboard.i: gameboard.c.i

.PHONY : gameboard.i

# target to preprocess a source file
gameboard.c.i:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/gameboard.c.i
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/gameboard.c.i
.PHONY : gameboard.c.i

gameboard.s: gameboard.c.s

.PHONY : gameboard.s

# target to generate assembly for a file
gameboard.c.s:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/gameboard.c.s
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/gameboard.c.s
.PHONY : gameboard.c.s

logic.o: logic.c.o

.PHONY : logic.o

# target to build an object file
logic.c.o:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/logic.c.o
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/logic.c.o
.PHONY : logic.c.o

logic.i: logic.c.i

.PHONY : logic.i

# target to preprocess a source file
logic.c.i:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/logic.c.i
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/logic.c.i
.PHONY : logic.c.i

logic.s: logic.c.s

.PHONY : logic.s

# target to generate assembly for a file
logic.c.s:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/logic.c.s
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/logic.c.s
.PHONY : logic.c.s

othello.o: othello.c.o

.PHONY : othello.o

# target to build an object file
othello.c.o:
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/othello.c.o
.PHONY : othello.c.o

othello.i: othello.c.i

.PHONY : othello.i

# target to preprocess a source file
othello.c.i:
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/othello.c.i
.PHONY : othello.c.i

othello.s: othello.c.s

.PHONY : othello.s

# target to generate assembly for a file
othello.c.s:
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/othello.c.s
.PHONY : othello.c.s

othello_tests.o: othello_tests.cc.o

.PHONY : othello_tests.o

# target to build an object file
othello_tests.cc.o:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello_tests.cc.o
.PHONY : othello_tests.cc.o

othello_tests.i: othello_tests.cc.i

.PHONY : othello_tests.i

# target to preprocess a source file
othello_tests.cc.i:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello_tests.cc.i
.PHONY : othello_tests.cc.i

othello_tests.s: othello_tests.cc.s

.PHONY : othello_tests.s

# target to generate assembly for a file
othello_tests.cc.s:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello_tests.cc.s
.PHONY : othello_tests.cc.s

player.o: player.c.o

.PHONY : player.o

# target to build an object file
player.c.o:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/player.c.o
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/player.c.o
.PHONY : player.c.o

player.i: player.c.i

.PHONY : player.i

# target to preprocess a source file
player.c.i:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/player.c.i
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/player.c.i
.PHONY : player.c.i

player.s: player.c.s

.PHONY : player.s

# target to generate assembly for a file
player.c.s:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/player.c.s
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/player.c.s
.PHONY : player.c.s

utility.o: utility.c.o

.PHONY : utility.o

# target to build an object file
utility.c.o:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/utility.c.o
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/utility.c.o
.PHONY : utility.c.o

utility.i: utility.c.i

.PHONY : utility.i

# target to preprocess a source file
utility.c.i:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/utility.c.i
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/utility.c.i
.PHONY : utility.c.i

utility.s: utility.c.s

.PHONY : utility.s

# target to generate assembly for a file
utility.c.s:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/utility.c.s
	$(MAKE) -f CMakeFiles/othello.dir/build.make CMakeFiles/othello.dir/utility.c.s
.PHONY : utility.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... othello_tests"
	@echo "... othello"
	@echo "... gameboard.o"
	@echo "... gameboard.i"
	@echo "... gameboard.s"
	@echo "... logic.o"
	@echo "... logic.i"
	@echo "... logic.s"
	@echo "... othello.o"
	@echo "... othello.i"
	@echo "... othello.s"
	@echo "... othello_tests.o"
	@echo "... othello_tests.i"
	@echo "... othello_tests.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

